DROP TABLE IF EXISTS employees;
 
CREATE TABLE users (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  firstname VARCHAR(250) NOT NULL,
  lastname VARCHAR(250) NOT NULL,
  username VARCHAR(250) NOT NULL,
  mail VARCHAR(250) NOT NULL UNIQUE,
  password VARCHAR(250) NOT NULL
);
 
